/*
 * Project Euler #2: Even Fibonacci numbers:
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 * 
 */
#include <cmath>
#include <cstdio>
#include <vector>
#include <iostream>
#include <algorithm>
#include <stdio.h>
using namespace std;

int main()
{
    long long int sum, N, F3, F6, temp;
    int T;
    cin >> T;
    while (T--)
    {
        sum = 0;
        F3 = 0;
        F6 = 2;
        cin >> N;
        while (F6 < N)
        {
            sum += F6;
            temp = F3;
            F3 = F6;
            F6 = 4 * F3 + temp;
        }
        printf("%lld\n", sum);
    }
    return 0;
}